# fly.toml app configuration file generated for goose-split-muddy-glade-9033 on 2023-12-24T14:02:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goose-split-muddy-glade-9033"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8090"
  
[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "goose_sqlite"
  destination = "pb_data"